import type { Metadata } from 'next';
import './globals.css';
import Header from '@/components/Header';
import ClientProvider from '@/components/ClientProvider';
import FirebaseAuthProvider from '@/components/FirebaseAuthProvider';
import { Kalam, Monoton } from 'next/font/google';
import { Toaster } from '@/components/ui/toaster';

export const metadata: Metadata = {
  title: 'Ecom',
  description: 'Generated by create next app',
};

const kalam = Kalam({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-kalam',
});
const monoton = Monoton({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-monoton',
});
export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <ClientProvider>
      <html lang="en">
        <FirebaseAuthProvider>
          <body className={`${kalam.variable} ${monoton.variable}`}>
            <Header />
            {modal}
            {children}
            <Toaster />
          </body>
        </FirebaseAuthProvider>
      </html>
    </ClientProvider>
  );
}
